name: test on macos-latest
on:
  pull_request:
    branches: main
  push:
    branches: [ci]
jobs:
  test-on-macos-latest:
    name: installing-test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - run: zsh install.zsh
        shell: zsh {0}
